#ifndef DRAW_H
#define DRAW_H

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define PLAYFIELD_TOP 24
#define PLAYFIELD_BOTTOM 216

#define BATTLE_ARENA_SIZE (PLAYFIELD_BOTTOM - PLAYFIELD_TOP)
#define BATTLE_LEFT ((SCREEN_WIDTH - BATTLE_ARENA_SIZE) / 2)
#define BATTLE_RIGHT (BATTLE_LEFT + BATTLE_ARENA_SIZE)
#define BATTLE_TOP PLAYFIELD_TOP
#define BATTLE_BOTTOM PLAYFIELD_BOTTOM

#define BG_COLOR 255
#define PADDLE_COLOR 0
#define BALL_COLOR 160
#define MENU_HIGHLIGHT_COLOR 28

#endif
