#include <fileioc.h>
#include <graphx.h>
#include <keypadc.h>
#include <tice.h>

#include "ball.h"
#include "battle.h"
#include "collision.h"
#include "cpu.h"
#include "draw.h"
#include "main.h"
#include "match.h"
#include "paddle.h"
#include "rally.h"
#include "save.h"

/* 24x24 flipper blade sprite, generated by scripts/gen_flipper_sprite.py:
 * an outlined, tapered blade with its hinge at the sprite center (12,12),
 * which is what gfx_RotatedScaledTransparentSprite rotates around. Rest
 * orientation points toward row 0 ("up"). Colors 0 and 160 match
 * PADDLE_COLOR and BALL_COLOR; 255 is the BG_COLOR transparent key. */
static const uint8_t flipperSpriteData[] = {
	24, 24, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 0, 0,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 0, 0, 160, 160, 0, 0, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 160, 160, 0,
	0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 0, 160, 160, 160, 160, 0, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 160, 160, 160, 160,
	0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 0, 160, 160, 160, 160, 0, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 160, 160, 160, 160,
	0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 0, 0, 160, 160, 160, 160, 0, 0, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 160, 160, 160, 160,
	0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 0, 160, 160, 160, 160, 160, 160, 0, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 160, 160, 160, 160, 160,
	160, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 0, 160, 160, 0, 0, 160, 160, 0, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 160, 160, 0, 0, 160,
	160, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 0, 160, 160, 160, 160, 160, 160, 0, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0, 0, 160, 160, 160, 160,
	0, 0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 0, 0, 0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
	255, 255,
};
static const gfx_sprite_t* flipperSprite = (const gfx_sprite_t*)flipperSpriteData;
#define FLIPPER_SPRITE_SIZE 24
#define FLIPPER_SPRITE_SCALE 64

typedef enum screen_t
{
	MENU_SCREEN,
	GAME_SCREEN
} screen_t;

typedef enum game_mode_t
{
	CPU_MODE,
	HIGH_SCORE_MODE,
	BATTLE_MODE
} game_mode_t;

static bool gameActive = true;
static bool secondWasDown = false;
static bool upWasDown = false;
static bool downWasDown = false;
static bool leftWasDown = false;
static bool rightWasDown = false;
static bool clearWasDown = false;
static screen_t currentScreen = MENU_SCREEN;
static game_mode_t selectedMode = CPU_MODE;
static game_mode_t activeMode = CPU_MODE;
static cpu_difficulty_t selectedDifficulty = CPU_NORMAL;
static cpu_difficulty_t activeDifficulty = CPU_NORMAL;
static int selectedBattleCount = BATTLE_MIN_COMBATANTS;
static int activeBattleCount = BATTLE_MIN_COMBATANTS;
static paddle_t playerPaddle;
static paddle_t cpuPaddle;
static ball_t ball;
static match_t match;
static rally_t rally;
static battle_t battle;
static unsigned int savedHighScore = 0;

static void startSelectedMode(void);
static void updateGame(void);
static void render(void);
static void renderMenu(void);
static void renderModeOption(int y, const char* title, const char* description, bool selected);
static const char* battleCombatantLabel(int count);
static void renderGame(void);
static void renderBattle(void);
static void renderBattleStatus(int index, int y);
static void renderServeOverlay(void);
static void renderMatchOverOverlay(void);
static void renderBattleOverOverlay(void);
static void persistHighScoreIfNeeded(void);
static void beforeGarbageCollection(void);
static void afterGarbageCollection(void);

int main(void)
{
	os_ClrHome();
	gfx_Begin();
	gfx_SetDrawBuffer();
	ti_SetGCBehavior(beforeGarbageCollection, afterGarbageCollection);

	initPaddle(&playerPaddle, PADDLE_LEFT);
	initPaddle(&cpuPaddle, PADDLE_RIGHT);
	initBall(&ball);
	initMatch(&match);
	initRally(&rally);
	savedHighScore = loadHighScore();
	rally.high_score = savedHighScore;

	do
	{
		updateKeyboard();
		if (!gameActive)
		{
			break;
		}

		if (currentScreen == GAME_SCREEN)
		{
			updateGame();
		}
		render();
	} while (gameActive);

	gfx_End();
	return 0;
}

void updateKeyboard(void)
{
	kb_Scan();

	bool secondIsDown = kb_Data[1] & kb_2nd;
	bool clearIsDown = kb_Data[6] & kb_Clear;
	bool downIsDown = kb_Data[7] & kb_Down;
	bool leftIsDown = kb_Data[7] & kb_Left;
	bool rightIsDown = kb_Data[7] & kb_Right;
	bool upIsDown = kb_Data[7] & kb_Up;

	if (currentScreen == MENU_SCREEN)
	{
		if (upIsDown && !upWasDown)
		{
			selectedMode = selectedMode == CPU_MODE
				? BATTLE_MODE
				: (game_mode_t)(selectedMode - 1);
		}
		else if (downIsDown && !downWasDown)
		{
			selectedMode = selectedMode == BATTLE_MODE
				? CPU_MODE
				: (game_mode_t)(selectedMode + 1);
		}

		if (selectedMode == CPU_MODE && leftIsDown && !leftWasDown)
		{
			selectedDifficulty = selectedDifficulty == CPU_EASY
				? CPU_HARD
				: selectedDifficulty - 1;
		}
		else if (selectedMode == CPU_MODE && rightIsDown && !rightWasDown)
		{
			selectedDifficulty = selectedDifficulty == CPU_HARD
				? CPU_EASY
				: selectedDifficulty + 1;
		}
		else if (selectedMode == BATTLE_MODE && leftIsDown && !leftWasDown)
		{
			selectedBattleCount = selectedBattleCount == BATTLE_MIN_COMBATANTS
				? BATTLE_MAX_COMBATANTS
				: selectedBattleCount - 1;
		}
		else if (selectedMode == BATTLE_MODE && rightIsDown && !rightWasDown)
		{
			selectedBattleCount = selectedBattleCount == BATTLE_MAX_COMBATANTS
				? BATTLE_MIN_COMBATANTS
				: selectedBattleCount + 1;
		}

		if (secondIsDown && !secondWasDown)
		{
			startSelectedMode();
		}
		else if (clearIsDown && !clearWasDown)
		{
			quit();
		}
	}
	else
	{
		paddle_t* activePlayerPaddle = activeMode == BATTLE_MODE
			? &battle.combatants[PADDLE_LEFT].paddle
			: &playerPaddle;

		if (downIsDown)
		{
			movePaddle(activePlayerPaddle, DOWN, PLAYER_PADDLE_SPEED);
		}
		else if (upIsDown)
		{
			movePaddle(activePlayerPaddle, UP, PLAYER_PADDLE_SPEED);
		}

		if (secondIsDown && !secondWasDown)
		{
			if (activeMode == BATTLE_MODE && battle.over)
			{
				initBattle(&battle, activeBattleCount, activeDifficulty);
				resetBall(&ball);
				serveBall(&ball, BALL_RIGHT);
			}
			else if (!ball.in_play)
			{
				if (activeMode == CPU_MODE && match.over)
				{
					initMatch(&match);
					initPaddle(&playerPaddle, PADDLE_LEFT);
					initPaddle(&cpuPaddle, PADDLE_RIGHT);
				}

				ball_direction_t direction = activeMode == CPU_MODE
					? match.next_serve_direction
					: BALL_RIGHT;
				serveBall(&ball, direction);
			}
		}

		if (clearIsDown && !clearWasDown)
		{
			persistHighScoreIfNeeded();
			currentScreen = MENU_SCREEN;
			resetBall(&ball);
		}
	}

	secondWasDown = secondIsDown;
	upWasDown = upIsDown;
	downWasDown = downIsDown;
	leftWasDown = leftIsDown;
	rightWasDown = rightIsDown;
	clearWasDown = clearIsDown;
}

void quit(void)
{
	gameActive = false;
}

static void startSelectedMode(void)
{
	activeMode = selectedMode;
	activeDifficulty = selectedDifficulty;
	activeBattleCount = selectedBattleCount;
	currentScreen = GAME_SCREEN;
	initPaddle(&playerPaddle, PADDLE_LEFT);
	initPaddle(&cpuPaddle, PADDLE_RIGHT);
	resetBall(&ball);

	if (activeMode == CPU_MODE)
	{
		initMatch(&match);
	}
	else if (activeMode == HIGH_SCORE_MODE)
	{
		resetRallyScore(&rally);
	}
	else
	{
		initBattle(&battle, activeBattleCount, activeDifficulty);
		serveBall(&ball, BALL_RIGHT);
	}
}

static void updateGame(void)
{
	if (activeMode == BATTLE_MODE)
	{
		updateBattle(&battle, &ball);
		return;
	}

	if (activeMode == CPU_MODE && match.over)
	{
		return;
	}

	if (activeMode == CPU_MODE)
	{
		updateCpuPaddle(&cpuPaddle, &ball, activeDifficulty);
	}

	ball_boundary_t rightBoundary = activeMode == CPU_MODE
		? BALL_GOAL_ON_RIGHT
		: BALL_WALL_ON_RIGHT;
	ball_update_t ballUpdate = updateBall(&ball, rightBoundary);

	if (activeMode == CPU_MODE)
	{
		if (ballUpdate != BALL_IN_PLAY)
		{
			recordPoint(&match, ballUpdate);
			resetBall(&ball);
		}
		else
		{
			checkPaddleCollision(&ball, &playerPaddle);
			checkPaddleCollision(&ball, &cpuPaddle);
		}
	}
	else if (ballUpdate == BALL_OUT_LEFT)
	{
		persistHighScoreIfNeeded();
		resetRallyScore(&rally);
		resetBall(&ball);
	}
	else if (checkPaddleCollision(&ball, &playerPaddle))
	{
		recordRallyHit(&rally);
	}
}

static void render(void)
{
	gfx_SetColor(BG_COLOR);
	gfx_FillRectangle(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT);
	gfx_SetTextFGColor(PADDLE_COLOR);

	if (currentScreen == MENU_SCREEN)
	{
		renderMenu();
	}
	else
	{
		renderGame();
	}

	gfx_SwapDraw();
}

static const char* battleCombatantLabel(int count)
{
	switch (count)
	{
		case 2:
			return "2 COMBATANTS";
		case 3:
			return "3 COMBATANTS";
		case 4:
		default:
			return "4 COMBATANTS";
	}
}

static void renderMenu(void)
{
	gfx_SetTextScale(2, 2);
	gfx_PrintStringXY("Paddlz", 112, 24);
	gfx_SetTextScale(1, 1);
	gfx_PrintStringXY("CHOOSE A MODE", 108, 50);

	renderModeOption(
		68,
		"CPU MATCH",
		selectedMode == CPU_MODE
			? cpuDifficultyName(selectedDifficulty)
			: "First to 5",
		selectedMode == CPU_MODE
	);
	if (selectedMode == CPU_MODE)
	{
		gfx_PrintStringXY("<", 72, 90);
		gfx_PrintStringXY(">", 144, 90);
	}
	renderModeOption(
		112,
		"HIGH SCORE",
		"Keep the rally alive",
		selectedMode == HIGH_SCORE_MODE
	);
	renderModeOption(
		156,
		"BATTLE ROYALE",
		selectedMode == BATTLE_MODE
			? battleCombatantLabel(selectedBattleCount)
			: "4-wall elimination",
		selectedMode == BATTLE_MODE
	);
	if (selectedMode == BATTLE_MODE)
	{
		gfx_PrintStringXY("<", 72, 178);
		gfx_PrintStringXY(">", 144, 178);
	}

	gfx_PrintStringXY("UP/DOWN: MODE", 104, 202);
	if (selectedMode == CPU_MODE)
	{
		gfx_PrintStringXY("LEFT/RIGHT: CPU LEVEL", 76, 214);
	}
	else if (selectedMode == BATTLE_MODE)
	{
		gfx_PrintStringXY("LEFT/RIGHT: COMBATANTS", 72, 214);
	}
	else
	{
		gfx_PrintStringXY("BEST SCORE IS SAVED", 84, 214);
	}
	gfx_PrintStringXY("2nd: SELECT  Clear: QUIT", 56, 226);
}

static void renderModeOption(
	int y,
	const char* title,
	const char* description,
	bool selected
)
{
	if (selected)
	{
		gfx_SetColor(MENU_HIGHLIGHT_COLOR);
		gfx_FillRectangle(60, y, 200, 40);
	}

	gfx_SetColor(PADDLE_COLOR);
	gfx_Rectangle(60, y, 200, 40);
	gfx_PrintStringXY(selected ? ">" : " ", 72, y + 6);
	gfx_PrintStringXY(title, 88, y + 6);
	gfx_PrintStringXY(description, 88, y + 22);
}

static void renderGame(void)
{
	if (activeMode == BATTLE_MODE)
	{
		renderBattle();
		return;
	}

	gfx_SetColor(PADDLE_COLOR);
	gfx_HorizLine(0, PLAYFIELD_TOP - 1, SCREEN_WIDTH);
	gfx_HorizLine(0, PLAYFIELD_BOTTOM, SCREEN_WIDTH);
	gfx_PrintStringXY("UP/DOWN: MOVE", 8, 224);
	gfx_PrintStringXY("Clear: MENU", 216, 224);

	if (activeMode == CPU_MODE)
	{
		for (int y = PLAYFIELD_TOP; y < PLAYFIELD_BOTTOM; y += 16)
		{
			gfx_FillRectangle(SCREEN_WIDTH / 2 - 1, y, 2, 8);
		}
		drawPaddle(&cpuPaddle);

		gfx_PrintStringXY("CPU MATCH", 8, 8);
		gfx_PrintStringXY(cpuDifficultyName(activeDifficulty), 88, 8);
		gfx_PrintStringXY("YOU", 168, 8);
		gfx_SetTextXY(200, 8);
		gfx_PrintUInt(match.player_score, 1);
		gfx_PrintStringXY(":", 216, 8);
		gfx_SetTextXY(232, 8);
		gfx_PrintUInt(match.cpu_score, 1);
		gfx_PrintStringXY("CPU", 248, 8);
	}
	else
	{
		gfx_PrintStringXY("HIGH SCORE", 8, 8);
		gfx_PrintStringXY("SCORE", 160, 8);
		gfx_SetTextXY(204, 8);
		gfx_PrintUInt(rally.score, 1);
		gfx_PrintStringXY("BEST", 232, 8);
		gfx_SetTextXY(268, 8);
		gfx_PrintUInt(rally.high_score, 1);
	}

	drawPaddle(&playerPaddle);
	drawBall(&ball);

	if (activeMode == CPU_MODE && match.over)
	{
		renderMatchOverOverlay();
	}
	else if (!ball.in_play)
	{
		renderServeOverlay();
	}

}

static void renderServeOverlay(void)
{
	const char *servePrompt = activeMode == CPU_MODE
		&& match.next_serve_direction == BALL_LEFT
		? "SERVE: TO YOU <"
		: activeMode == CPU_MODE
			? "SERVE: TO CPU >"
			: "SERVE: TO WALL >";

	gfx_SetColor(BG_COLOR);
	gfx_FillRectangle(87, 88, 146, 64);
	gfx_SetColor(PADDLE_COLOR);
	gfx_Rectangle(87, 88, 146, 64);
	gfx_PrintStringXY(servePrompt, 96, 106);
	gfx_PrintStringXY("Press 2nd", 124, 126);
}

static void renderMatchOverOverlay(void)
{
	const char *winner = match.player_score > match.cpu_score
		? "YOU WIN"
		: "CPU WINS";

	gfx_SetColor(BG_COLOR);
	gfx_FillRectangle(87, 88, 146, 64);
	gfx_SetColor(PADDLE_COLOR);
	gfx_Rectangle(87, 88, 146, 64);
	gfx_PrintStringXY(winner, 128, 104);
	gfx_PrintStringXY("2nd: NEW MATCH", 100, 126);
}

static void renderBattle(void)
{
	gfx_SetColor(PADDLE_COLOR);
	gfx_Rectangle(BATTLE_LEFT, BATTLE_TOP, BATTLE_ARENA_SIZE, BATTLE_ARENA_SIZE);
	gfx_PrintStringXY("BATTLE ROYALE", 8, 8);
	gfx_PrintStringXY("Clear: MENU", 216, 224);

	for (int i = 0; i < BATTLE_MAX_COMBATANTS; i++)
	{
		combatant_t* combatant = &battle.combatants[i];

		if (combatant->alive)
		{
			drawPaddle(&combatant->paddle);
		}
		else if (!battle.over && combatant->flip_timer > 0)
		{
			point_t hinge = battleFlipperHinge((paddle_side_t)i, combatant->flip_tangent);
			int angle = battleFlipperAngle((paddle_side_t)i, combatant->flip_tangent, combatant->flip_timer);
			gfx_SetTransparentColor(BG_COLOR);
			gfx_RotatedScaledTransparentSprite_NoClip(
				flipperSprite,
				hinge.x - FLIPPER_SPRITE_SIZE / 2,
				hinge.y - FLIPPER_SPRITE_SIZE / 2,
				(uint8_t)angle,
				FLIPPER_SPRITE_SCALE
			);
		}

		renderBattleStatus(i, BATTLE_TOP + i * (BATTLE_ARENA_SIZE / BATTLE_MAX_COMBATANTS));
	}

	drawBall(&ball);

	if (battle.over)
	{
		renderBattleOverOverlay();
	}
}

static void renderBattleStatus(int index, int y)
{
	static const char* wallLabels[BATTLE_MAX_COMBATANTS] = { "LEFT", "RIGHT", "TOP", "BOT" };
	const combatant_t* combatant = &battle.combatants[index];
	const char* status = combatant->controller == COMBATANT_PLAYER && combatant->alive
		? "YOU"
		: combatant->alive ? "CPU" : "OUT";

	gfx_SetColor(PADDLE_COLOR);
	gfx_PrintStringXY(wallLabels[index], BATTLE_RIGHT + 4, y);
	gfx_PrintStringXY(status, BATTLE_RIGHT + 4, y + 10);
}

static void renderBattleOverOverlay(void)
{
	const char *winner = battleWinner(&battle) == PADDLE_LEFT
		? "YOU WIN"
		: "CPU WINS";

	gfx_SetColor(BG_COLOR);
	gfx_FillRectangle(87, 88, 146, 64);
	gfx_SetColor(PADDLE_COLOR);
	gfx_Rectangle(87, 88, 146, 64);
	gfx_PrintStringXY(winner, 128, 104);
	gfx_PrintStringXY("2nd: NEW MATCH", 100, 126);
}

static void persistHighScoreIfNeeded(void)
{
	if (rally.high_score > savedHighScore
		&& saveHighScore(rally.high_score)) {
		savedHighScore = rally.high_score;
	}
}

static void beforeGarbageCollection(void)
{
	gfx_End();
}

static void afterGarbageCollection(void)
{
	gfx_Begin();
	gfx_SetDrawBuffer();
}
